# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtraining',
            name='place',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
