# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt', '0002_scheduledtraining_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=1024)),
                ('text', models.TextField()),
            ],
        ),
    ]
