# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vingtsunkuen', '0003_auto_20161202_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='site',
            field=models.CharField(default='vt', max_length=2),
        ),
    ]
